acwedding/acwedding/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^faq/', include('faq.urls', namespace='faq')),
    url(r'^area-information/', include('tourisminfo.urls', namespace='tourisminfo')),
    url(r'^', include('pages.urls', namespace='pages')),
)

acwedding/faq/urls.py
from django.conf.urls import patterns, url

from .views import IndexView

urlpatterns = patterns('',
    url(r'^', IndexView.as_view(), name="index"),
)

acwedding/tourisminfo/urls.py
from django.conf.urls import patterns, url

from .views import (AccommodationDetailView, AccommodationIndexView, 
    PointOfInterestIndexView, PointOfInterestDetailView
)

urlpatterns = patterns('',
    url(r'^accommodations/$',
        AccommodationIndexView.as_view(),
        name='accommodations_index'
    ),
    url(r'^accommodations/(?P<slug>[\w-]+)/$', 
        AccommodationDetailView.as_view(), 
        name="accommodation_detail"
    ),
    url(r'^attractions-and-food/$', 
        PointOfInterestIndexView.as_view(), 
        name="attractions_index"
    ),
    url(r'^attractions-and-food/(?P<slug>[\w-]+)/$', 
        PointOfInterestDetailView.as_view(), 
        name="attraction_detail"
    ),
)

acwedding/tourisminfo/models.py
from django.contrib.contenttypes import generic
from django.core.exceptions import ValidationError
from django.db import models

from core.models import CustomTextField, Image, GenericLink
from googlemaps.models import Marker

class BasePointOfInterest(models.Model):
    # To decouple this model from this project, use core.Location instead of 
    # googlemaps.Marker for similar functionality (Marker has a Location 
    # attribute).
    description = CustomTextField()
    marker = models.ForeignKey(Marker)
    review = CustomTextField(blank=True)
    highlight = models.BooleanField(default=False)
    external_links = generic.GenericRelation(GenericLink, verbose_name="External links")
    short_description = models.CharField(max_length=128)
    image = models.ForeignKey(Image, null=True, blank=True)
    
    def __str__(self):
        return self.full_name
        
    @property
    def full_name(self):
        return self.marker.location.full_name
        
    @property
    def location(self):
        return self.marker.location
        
    @property
    def slug(self):
        return self.marker.location.slug
    
    class Meta:
        abstract = True

class PointOfInterest(BasePointOfInterest):
    CATEGORY_CHOICES = (
        ('attractions', 'Things to Do'),
        ('food', 'Food & Drink'),
        ('lighthouses', 'Lighthouses'),
    )
    category = models.CharField(max_length=16, choices=CATEGORY_CHOICES)
    
    class Meta:
        verbose_name_plural = 'Points of interest'
        ordering = ['marker__location__full_name']
    
class Accommodation(BasePointOfInterest):
    CATEGORY_CHOICES = (
        ('hotel', 'Hotels'),
        ('motel', 'Motels'),
        ('bandb', 'Bed and Breakfast'),
        ('cabin', 'Cabins / Cottages / Campgrounds / RV Parks'),
    )
    category = models.CharField(max_length=16, choices=CATEGORY_CHOICES)
    category2 = models.CharField(max_length=16, choices=CATEGORY_CHOICES, 
        blank=True, null=True
    )
    amenities = CustomTextField(blank=True)
    
    def validate_unique(self, **kwargs):
        if self.category == self.category2:
            raise ValidationError('Categories must be unique')
            
        return super().validate_unique(**kwargs)
        
    class Meta:
        ordering = ['marker__location__full_name']

acwedding/tourisminfo/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import DetailView, ListView

from .models import Accommodation, PointOfInterest
from googlemaps.models import Marker

class BasePointOfInterestDetailView(DetailView):
    context_object_name = 'poi'

    try:
        ceremony_marker = Marker.objects.get(name='ceremony')
    except ObjectDoesNotExist:
        ceremony_marker = None
        
    try:
        reception_marker = Marker.objects.get(name='reception')
    except ObjectDoesNotExist:
        reception_marker = None
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ceremony_marker'] = self.ceremony_marker
        context['reception_marker'] = self.reception_marker
        
        return context

    def get_slug_field(self):
        return 'marker__location__slug'

class BasePointOfInterestIndexView(ListView):
    context_object_name = 'poi_list'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = self.model.CATEGORY_CHOICES
        
        return context
        
class AccommodationDetailView(BasePointOfInterestDetailView):
    model = Accommodation
    template_name = 'tourisminfo/accommodation_detail.html'

class AccommodationIndexView(BasePointOfInterestIndexView):
    model = Accommodation
    template_name = 'tourisminfo/accommodations_index.html'
    queryset = Accommodation.objects.exclude(highlight=True)

class PointOfInterestIndexView(BasePointOfInterestIndexView):
    model = PointOfInterest
    template_name = 'tourisminfo/poi_index.html'

class PointOfInterestDetailView(BasePointOfInterestDetailView):
    model = PointOfInterest
    template_name = 'tourisminfo/poi_detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subheader_image'] = self.object.image
        
        return context

acwedding/templates/tourisminfo/accommodation_detail.html
{% extends 'tourisminfo/poi_detail.html' %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'tourisminfo:accommodations_index' %}">Accommodations</a></li>
        <li class="active">{{ poi.full_name }}</li>
    </ol>
{% endblock breadcrumb %}

{% block extra_sections %}
    {% if poi.amenities %}
        <section>
            <h3>Amenities</h3>
            {{ poi.amenities|safe }}
        </section>
    {% endif %}
{% endblock extra_sections %}

acwedding/templates/tourisminfo/accommodations_index.html
{% extends 'tourisminfo/base_poi_index.html' %}

{% block page_title %}{% block h2 %}Accommodations{% endblock h2 %}{% endblock page_title %}

{% block page_description_whole %}
    <section>
        <h3>Sanctuary Inn</h3>
        <p>We recommend staying at the Sanctuary Inn near downtown Alpena. We have a block of rooms reserved there at a discounted rate, and we are providing a complimentary shuttle between this hotel and the reception. <a href="/area-information/accommodations/sanctuary-inn/">Click here for more information.</a></p>
    </section>
{% endblock page_description_whole %}

{% block categories %} 
    <section>
        <h3>Other Options</h3>
        <p>Below is a list of additional lodging options in the Alpena, Presque Isle, and Hubbard Lake areas. Click an option for more information.</p>
{% endblock categories %}

{% block post_list %}</section>{% endblock %}

{% block empty_description %}No accommodation information available at this time{% endblock empty_description %}

{% block detail_url %}{% url 'tourisminfo:accommodation_detail' poi.slug %}{% endblock %}

acwedding/templates/tourisminfo/base_poi_index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    {% block page_description_whole %}
        <div class="text-center">
            {% block page_description %}{% endblock page_description %}
        </div>
    {% endblock page_description_whole %}
    
    {% block categories %}
    <div class="text-center checkbox-group">
        <p><em>Click a checkbox to filter list. <br>Click anywhere in a list item to view more information.</em></p>
        {% for category in categories %}
            <div class="checkbox areainfo-checkbox">
                <label>
                    <input type="checkbox" name="{{ category.0 }}" checked="true">{{ category.1 }}
                </label>
            </div>
        {% endfor %}
    </div>
    {% endblock categories %}
    
    <div class="list-group areainfo-list-group">
        {% for poi in poi_list %}
            <a href="{% block detail_url %}{% endblock detail_url %}" alt="More information" class="list-group-item {% if poi.highlight %}list-group-item-highlight {% endif %}{{ poi.category }}{% if poi.category2 %} {{ poi.category2 }}{% endif %}">
                    <img src="{% static poi.marker.icon.static_path %}" class="pull-right">
                    {% if poi.highlight %}<img src="{% static 'images/map_icons/mickey_thumb.png' %}" title="A Claire and Adam favorite&#8482;" class="pull-right">{% endif %}
                    <h4 class="list-group-item-heading">{{ poi.full_name }}</h4>
                    <p class="list-group-item-text">{{ poi.short_description }}</p>
            </a>
        {% empty %}
            <p class="text-center"><strong>
                {% block empty_description %}No listings available at this time{% endblock empty_description %}
            </strong></p>
        {% endfor %}
    </div>
    
    {% block post_list %}{% endblock %}
{% endblock content %}

{% block body_end %}
    <script type="text/javascript">
        $(document).ready(function() {
            $(':checkbox').prop('checked', true);

            $(':checkbox').change(function() {
                $('.'+this.name).slideToggle(300);
            });
        });
    </script>
{% endblock body_end %}

acwedding/templates/tourisminfo/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load core_tags %}
{% load googlemaps_tags %}

{% block page_title %}{{ poi.full_name }}{% endblock page_title %}

{% block h2 %}
    <img src="{% static 'images/map_icons/'|add:poi.marker.icon.filename %}" class="hidden-xs">
    &nbsp;&nbsp;{{ poi.full_name }}&nbsp;&nbsp;
    <img src="{% static 'images/map_icons/'|add:poi.marker.icon.filename %}"  class="hidden-xs">
{% endblock %}

{% block extra_css %}<link rel="stylesheet" type="text/css" href="{% static 'css/gmap.css' %}" />{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'tourisminfo:attractions_index' %}">Attractions &amp; Food</a></li>
        <li class="active">{{ poi.full_name }}</li>
    </ol>
{% endblock breadcrumb %}

{% block content %}
    {% if poi.image %}
        <div class="subheader-img-wrapper">
                <img src="{% static 'images/tourisminfo/'|add:poi.image.filename %}" class="img-responsive center-block">
                {% if poi.image.subtitle %}
                    <p class="text-center">{{ poi.image.subtitle }}</p>
                {% endif %} 
        </div>
    {% endif %}

    <div id="primary-text">
        <section>
            <h3>Description</h3>
            <p>{{ poi.description|safe|reverseurls|linebreaks }}<p>
        </section>
        
        {% if poi.review %}
        <section>
            <h3>Claire &amp; Adam's Review</h3>
            <p>{{ poi.review|safe|reverseurls|linebreaks }}</p>
        </section>
        {% endif %}
        
        <section>
            <h3>External Links</h3>
            <a href="{{ poi.link }}">{{ poi.link_description }}</a><br>
        </section>

        <section>
            <h3>Map</h3>

            <div class="gmap-wrapper hidden-xs text-center">
                <div id="map_canvas"></div>
                <p>
                    Note: The ceremony and reception sites are indicated with pink markers.<br>
                    <a href="https://www.google.com/maps/place/{{ poi.marker.lat|linkablelatitude }}+{{ poi.marker.long|linkablelongitude }}/@{{ poi.marker.lat }},{{ poi.marker.long }},15z">View at Google Maps</a>
                </p>
            </div>
            <p class="visible-xs"><strong><a href="https://www.google.com/maps/place/{{ poi.marker.lat|linkablelatitude }}+{{ poi.marker.long|linkablelongitude }}/@{{ poi.marker.lat }},{{ poi.marker.long }},15z">View location at Google Maps.</a></strong><br>Embedded map available on larger devices.</p>
        </section>

        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAxCuyULS1j9utodXGtNfFQs1fpe0nwoXM&sensor=false"></script>
        <script type="text/javascript">
        function initialize() {
            var map_canvas = document.getElementById('map_canvas');
            var map_options = {
                center: new google.maps.LatLng({{ poi.marker.lat }}, {{ poi.marker.long }}),
                zoom: 12,
                mapTypeControl: true,
                mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
                mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            
            var map = new google.maps.Map(map_canvas, map_options);
            
            var {{ poi.marker.name }}Marker = new google.maps.Marker({
                position: new google.maps.LatLng({{ poi.marker.lat }}, {{ poi.marker.long }}),
                map: map,
                title: "{{ poi.marker.full_name|safe }}",
                icon: "{% static 'images/map_icons/'|add:poi.marker.icon.filename %}"
            });
            
            var ceremonyMarker = new google.maps.Marker({
                position: new google.maps.LatLng({{ ceremonyMarker.lat }}, {{ ceremonyMarker.long }}),
                map: map,
                title: "{{ ceremonyMarker.full_name }}",
                icon: "{% static 'images/map_icons/'|add:ceremonyMarker.icon.filename %}"
            });
            
            var receptionMarker = new google.maps.Marker({
                position: new google.maps.LatLng({{ receptionMarker.lat }}, {{ receptionMarker.long }}),
                map: map,
                title: "{{ receptionMarker.full_name }}",
                icon: "{% static 'images/map_icons/'|add:receptionMarker.icon.filename %}"
            });
        }
        google.maps.event.addDomListener(window, 'load', initialize);
        </script>
    </div>
{% endblock content %}

acwedding/templates/tourisminfo/poi_detail.html
{% extends 'base_content_header_img.html' %}
{% load staticfiles %}
{% load core_tags %}
{% load googlemaps_tags %}

{% block page_title %}{{ poi.location.full_name }}{% endblock page_title %}

{% block h2 %}
    <img src="{% static poi.marker.icon.static_path %}" class="hidden-xs">
    &nbsp;&nbsp;{{ poi.full_name }}&nbsp;&nbsp;
    <img src="{% static poi.marker.icon.static_path %}"  class="hidden-xs">
{% endblock %}

{% block extra_css %}<link rel="stylesheet" type="text/css" href="{% static 'css/gmap.min.css' %}">{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'tourisminfo:attractions_index' %}">Attractions &amp; Food</a></li>
        <li class="active">{{ poi.full_name }}</li>
    </ol>
{% endblock breadcrumb %}

{% block content %}
    <section>
        <h3>Description</h3>
        {{ poi.description|safe|linebreaks }}
    </section>
    
    {% if poi.review %}
    <section>
        <h3>Claire &amp; Adam's Review</h3>
        {{ poi.review|safe|linebreaks }}
    </section>
    {% endif %}
    
    {% block extra_sections %}{% endblock extra_sections %}
    
    <section>
        <h3>External Links</h3>
        {% for link in poi.external_links.all %}
            <a href="{{ link.url }}" title="{{ link.title }}" target="_blank">{{ link.text }}</a><br>
        {% endfor %}
    </section>

    <section>
        <h3>Map</h3>
        <div class="gmap-wrapper hidden-xs text-center">
            <div id="map_canvas"></div>
            <p>
                Note: The ceremony and reception sites are indicated with pink markers.<br>
                <a href="https://www.google.com/maps/place/{{ poi.location.latitude|linkablelatitude }}+{{ poi.location.longitude|linkablelongitude }}/@{{ poi.location.latitude }},{{ poi.location.longitude }},15z">View at Google Maps</a>
            </p>
        </div>
        <p class="visible-xs"><strong><a href="https://www.google.com/maps/place/{{ poi.location.latitude|linkablelatitude }}+{{ poi.location.longitude|linkablelongitude }}/@{{ poi.location.latitude }},{{ poi.location.longitude }},15z">View location at Google Maps.</a></strong><br>Embedded map available on larger devices.</p>
    </section>

    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAxCuyULS1j9utodXGtNfFQs1fpe0nwoXM&sensor=false"></script>
    <script type="text/javascript">
    function initialize() {
        var map_canvas = document.getElementById('map_canvas');
        var map_options = {
            center: new google.maps.LatLng({{ poi.location.latitude }}, {{ poi.location.longitude }}),
            zoom: 12,
            mapTypeControl: true,
            mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        
        var map = new google.maps.Map(map_canvas, map_options);
        
        var {{ poi.marker.name }}Marker = new google.maps.Marker({
            position: new google.maps.LatLng({{ poi.location.latitude }}, {{ poi.location.longitude }}),
            map: map,
            title: "{{ poi.marker.location.full_name|safe }}",
            icon: "{% static 'images/map_icons/'|add:poi.marker.icon.filename %}"
        });
        
        {% if ceremony_marker %}
            var ceremonyMarker = new google.maps.Marker({
                position: new google.maps.LatLng({{ ceremony_marker.location.latitude }}, {{ ceremony_marker.location.longitude }}),
                map: map,
                title: "{{ ceremony_marker.location.full_name }}",
                icon: "{% static ceremony_marker.icon.static_path %}"
            });
        {% endif %}
        
        {% if reception_marker %}
            var receptionMarker = new google.maps.Marker({
                position: new google.maps.LatLng({{ reception_marker.location.latitude }}, {{ reception_marker.location.longitude }}),
                map: map,
                title: "{{ reception_marker.location.full_name }}",
                icon: "{% static reception_marker.icon.static_path %}"
            });
        {% endif %}
    }
    google.maps.event.addDomListener(window, 'load', initialize);
    </script>
{% endblock content %}

acwedding/templates/tourisminfo/poi_index.html
{% extends 'tourisminfo/base_poi_index.html' %}

{% block page_title %}{% block h2 %}Alpena Area Attractions &amp; Food{% endblock h2 %}{% endblock page_title %}

{% block page_description %}
    <p>Planning to stay the weekend? Looking for lunch before the ceremony? This page lists attractions, shops, and restaurants in the Alpena region. Only attractions likely to be open at the time of our wedding are listed; for year-round information, visit the <a href="http://www.alpenacvb.com/">Alpena CVB Website</a>.</p>
{% endblock page_description %}

{% block empty_description %}No attraction or food information available at this time{% endblock empty_description %}

{% block detail_url %}{% url 'tourisminfo:attraction_detail' poi.slug %}{% endblock %}