acwedding/faq/urls.py
from django.conf.urls import patterns, url

from .views import IndexView

urlpatterns = patterns('',
    url(r'^', IndexView.as_view(), name="index"),
)

acwedding/faq/models.py
from django.db import models

from core.models import CustomTextField

class Entry(models.Model):
    
    # Note id is explicit here so it can be easily edited via the
    # admin site. The order questions appear is based on the id
    # field; It's likely a user may want to edit that order.
    id = models.PositiveSmallIntegerField(primary_key=True)
    question = models.CharField(max_length=75)
    answer = CustomTextField()

    def __str__(self):
        return "{0} - {1}".format(str(self.id), str(self.question))
        
    class Meta:
        ordering = ['id']
        verbose_name_plural = 'Entries'

acwedding/faq/views.py
from django.views.generic import ListView

from .models import Entry

class IndexView(ListView):
    template_name = 'faq/index.html'
    model = Entry

acwedding/templates/faq/index.html
{% extends 'base.html' %}

{% block page_title %}{% block h2 %}FAQ{% endblock h2 %}{% endblock page_title %}

{% block content-col-extraclass  %}faq{% endblock %}

{% block content %}
    <div class="faq">
        {% for entry in entry_list %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><strong>{{ entry.question }}</strong></h3>
            </div>
            <div class="panel-body">{{ entry.answer|safe}}</div>
        </div>
        {% empty %}
        <p class="text-center">No FAQ entries at this time.</p>
        {% endfor %}
    </div>
{% endblock content %}