acwedding/acwedding/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^faq/', include('faq.urls', namespace='faq')),
    url(r'^area-information/', include('tourisminfo.urls', namespace='tourisminfo')),
    url(r'^', include('pages.urls', namespace='pages')),
)

acwedding/faq/urls.py
from django.conf.urls import patterns, url

from .views import IndexView

urlpatterns = patterns('',
    url(r'^', IndexView.as_view(), name="index"),
)

acwedding/tourisminfo/urls.py
from django.conf.urls import patterns, url

from .views import (AccommodationDetailView, AccommodationIndexView, 
    PointOfInterestIndexView, PointOfInterestDetailView
)

urlpatterns = patterns('',
    url(r'^accommodations/$',
        AccommodationIndexView.as_view(),
        name='accommodations_index'
    ),
    url(r'^accommodations/(?P<slug>[\w-]+)/$', 
        AccommodationDetailView.as_view(), 
        name="accommodation_detail"
    ),
    url(r'^attractions-and-food/$', 
        PointOfInterestIndexView.as_view(), 
        name="attractions_index"
    ),
    url(r'^attractions-and-food/(?P<slug>[\w-]+)/$', 
        PointOfInterestDetailView.as_view(), 
        name="attraction_detail"
    ),
)

acwedding/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/icons/apple-touch-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/icons/apple-touch-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/icons/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/icons/apple-touch-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/icons/apple-touch-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/icons/apple-touch-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/icons/apple-touch-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/icons/apple-touch-icon-152x152.png' %}">
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon-196x196.png' %}" sizes="196x196">
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon-160x160.png' %}" sizes="160x160">
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon-96x96.png' %}" sizes="96x96">
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon-16x16.png' %}" sizes="16x16">
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon-32x32.png' %}" sizes="32x32">
    <meta name="msapplication-TileColor" content="#603cba">
    <meta name="msapplication-TileImage" content="{% static 'images/icons/mstile-144x144.png' %}">
    
    <title>{% block full_page_title %}{% block page_title %}{% endblock page_title %} | Beagle-Madill Wedding{% endblock full_page_title %}</title>

    <link href='http://fonts.googleapis.com/css?family=News+Cycle' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-custom.min.css' %}" rel="stylesheet">
    {% block extra_css %}{% endblock %}
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <link href="{% static 'css/iefixes.css' %}" rel="stylesheet">
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extra_js %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--<a class="navbar-brand visible-lg-inline visible-md-inline" href="/">Beagle-Madill Wedding</a>-->
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dopdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">about us<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'pages:detail' 'bride-and-groom' %}" title="About the Bride and Groom">Bride &amp; Groom</a></li>
                            <li><a href="{% url 'pages:detail' 'kittens' %}" title="A page about our babies">The Pets</a></li>
                            <li><a href="{% url 'pages:detail' 'wedding-party' %}" title="Wedding Party">Wedding Party</a></li>
                            <li><a href="{% url 'pages:detail' 'engagement' %}" title="Engagement">Engagement</a></li>
                            <li><a href="{% url 'pages:detail' 'galleries' %}" title="Photo Galleries">Photo Galleries</a></li>
                        </ul>
                    </li>
                    <li class="dopdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">guest information<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'pages:detail' 'ceremony' %}" title="Ceremony">Ceremony</a></li>
                            <li><a href="{% url 'pages:detail' 'reception' %}" title="Reception">Reception</a></li>
                            <li><a href="{% url 'pages:detail' 'registry' %}" title="Registry">Registry</a></li>
                            <li><a href="{% url 'pages:detail' 'transportation' %}" title="Transportation">Transportation</a></li>
                        </ul>
                    </li>
                    <li class="dopdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">area information<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'tourisminfo:accommodations_index' %}" title="Hotel, motel, and cabin options">Accommodations</a></li>
                            <li><a href="{% url 'tourisminfo:attractions_index' %}" title="Attractions and Food">Attractions &amp; Food</a></li>
                            <li><a href="{% url 'pages:detail' 'history' %}" title="History">History</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'faq:index' %}">FAQ</a></li>
                    <li><a href="{% url 'pages:detail' 'vendors' %}" title="Vendors">Vendors</a></li>
                    <li><a href="{% url 'pages:contact' %}">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    
    <header class="jumbotron">
        <div class="container">
            <h1><a href="/">Claire &amp; Adam's Wedding!</a></h1>
            <h2 class="subheading">May 16, 2015 &nbsp;&nbsp; Alpena, MI</span>
        </div>
    </header>
    
    {% block breadcrumb %}{% endblock %}

    <div id="content-container" class="container">
        <h2 class="text-center">{% block h2 %}{% endblock %}</h2>
        <div class="row">
            <div id="content-col" class="col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2 {% block content-col-extraclass  %}{% endblock %}">
                {% block content_header %}
                {% endblock %}
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    
    <footer>
        <div class="container">
            <span class="pull-right">&copy; 2014 Adam Beagle. <span class="hidden-xs">Powered by <a href="http://www.djangoproject.com/" title="The Django Project">Django</a>. View source <a href="https://github.com/adambeagle/acweddingsite">at Github.</a></span></span>
        </div>
    </footer>
    
    <!-- Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-54434515-1', 'auto');
        ga('send', 'pageview');
    </script>
    
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    
    <script type='text/javascript'>
        $(window).load(function() {
            originalPadding = parseInt($( 'body > .container' ).css('padding-bottom'), 10);
            newPadding = originalPadding + ($( window ).height() - $( 'body' ).height());
            if (newPadding > originalPadding) {
                $( 'body > .container' ).css('padding-bottom', newPadding + 'px');
            }
        });
    </script>
    {% block body_end %}{% endblock %}
</body>

</html>

acwedding/templates/base_content_header_img.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load core_tags %}

{% comment %}NOTE this template expects a context variable named subheader_image, with attributes as in core.models.BaseImage{% endcomment %}

{% block extra_js %}
    <script src="{% static 'js/picturefill.min.js' %}" async></script>
{% endblock extra_js %}

{% block content_header %}
    {% if subheader_image %}
        <div class="subheader-img-wrapper center-block">
                <picture alt="{{ subheader_image.alt_text }}">
                    <!--[if IE 9]><video style="display: none;"><![endif]-->
                    <source srcset="{% static subheader_image.static_path %}" media="(min-width:1201px)">
                    <source srcset="{% static subheader_image.static_path|filenamesuffix:'_l' %}" media="(min-width:993px)">
                    <source srcset="{% static subheader_image.static_path|filenamesuffix:'_m' %}" media="(min-width:769px)">
                    <source srcset="{% static subheader_image.static_path|filenamesuffix:'_s' %}" media="(min-width:481px)">
                    <!--[if IE 9]></video><![endif]-->
                    <img srcset="{% static subheader_image.static_path|filenamesuffix:'_xs' %}">
                </picture>
        
                {% if subheader_image.caption %}
                    <p class="text-center">{{ subheader_image.caption|safe }}</p>
                {% endif %}
        </div>
    {% endif %}
{% endblock content_header %}